// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.220531.1

#pragma once
#ifndef WINRT_Minesweeper_H
#define WINRT_Minesweeper_H
#include "winrt/base.h"
static_assert(winrt::check_version(CPPWINRT_VERSION, "2.0.220531.1"), "Mismatched C++/WinRT headers.");
#define CPPWINRT_VERSION "2.0.220531.1"
#include "winrt/impl/Windows.UI.Composition.2.h"
#include "winrt/impl/Windows.UI.Xaml.2.h"
#include "winrt/impl/Windows.UI.Xaml.Controls.2.h"
#include "winrt/impl/Minesweeper.2.h"
namespace winrt::impl
{
    template <typename D> auto consume_Minesweeper_IsfmlMain<D>::MyProperty() const
    {
        int32_t value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::Minesweeper::IsfmlMain)->get_MyProperty(&value));
        return value;
    }
    template <typename D> auto consume_Minesweeper_IsfmlMain<D>::MyProperty(int32_t value) const
    {
        check_hresult(WINRT_IMPL_SHIM(winrt::Minesweeper::IsfmlMain)->put_MyProperty(value));
    }
    template <typename D>
    struct produce<D, winrt::Minesweeper::IsfmlMain> : produce_base<D, winrt::Minesweeper::IsfmlMain>
    {
        int32_t __stdcall get_MyProperty(int32_t* value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *value = detach_from<int32_t>(this->shim().MyProperty());
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall put_MyProperty(int32_t value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().MyProperty(value);
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
}
WINRT_EXPORT namespace winrt::Minesweeper
{
    inline sfmlMain::sfmlMain() :
        sfmlMain(impl::call_factory_cast<sfmlMain(*)(winrt::Windows::Foundation::IActivationFactory const&), sfmlMain>([](winrt::Windows::Foundation::IActivationFactory const& f) { return f.template ActivateInstance<sfmlMain>(); }))
    {
    }
}
namespace std
{
#ifndef WINRT_LEAN_AND_MEAN
    template<> struct hash<winrt::Minesweeper::IsfmlMain> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Minesweeper::sfmlMain> : winrt::impl::hash_base {};
#endif
#ifdef __cpp_lib_format
#endif
}
#endif
