// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.220531.1

#pragma once
#ifndef WINRT_Minesweeper_1_H
#define WINRT_Minesweeper_1_H
#include "winrt/impl/Minesweeper.0.h"
WINRT_EXPORT namespace winrt::Minesweeper
{
    struct __declspec(empty_bases) IsfmlMain :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IsfmlMain>
    {
        IsfmlMain(std::nullptr_t = nullptr) noexcept {}
        IsfmlMain(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
}
#endif
